# -*- coding: utf-8 -*-
"""KeyWord_Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hj-ohYdobRXnHDQ8kUcE0KvAc-ng8dEZ
"""

pip install keybert

from google.colab import drive 
drive.mount('/content/drive')

import pandas as pd
from keybert import KeyBERT
doc = """
         Supervised learning is the machine learning task of learning a function that
         maps an input to an output based on example input-output pairs. 
      """
kw_model = KeyBERT()
keywords = kw_model.extract_keywords(doc)
#for x in range( 1016 ) :
#  print( "Title : " , df['title'][x] ) 
from google.colab import files
history = files.upload()
from keybert import KeyBERT
import pandas as pd 
df = pd.read_csv( '/content/drive/MyDrive/Final year project/history (1).csv' )
for x in range(1016) :
  doc = df['title'][x]
  kw_model = KeyBERT()
  key = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 3) , top_n=1 )
 
  print ( "Title : " , df['title'][x] , "    Keyword : " , key )